---

- hosts: all
  become: true
  pre_tasks:
  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: mariadb_server
  become: true
  roles:
    - mariadb_server
  vars_files:
    - vars.yml
  handlers:
  - name: Restart mariadb
    service:
      name: mariadb
      state: restarted

