---

- hosts: all
  become: true
  pre_tasks:
  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: my_server
  become: true
  roles:
    - docker_setup